### ***Problem03***

    DATATSET : 20 NewsGroups : news articles
    (https://en.wikipedia.org/wiki/MNIST_database)
    DATATSET : MNIST : digit images
    (http://yann.lecun.com/exdb/mnist/)

In [6]:
### Drive mount & Import library 
from google.colab import drive 
drive.mount("/content/drive")
import numpy as np 
import pandas as pd 
import time

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [7]:
### 20 New Groups Data set 
# Import data set
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import TfidfVectorizer 
ng_df = fetch_20newsgroups()

In [8]:
### Normalize features (TF-IDF) 
vectorizer = TfidfVectorizer() 
ng_df_normalized = vectorizer.fit_transform(ng_df.data) 
# Make to Subset
from sklearn.model_selection import train_test_split  
X_train, X_test = train_test_split(ng_df_normalized, test_size=0.3) 

In [13]:
### Compute Similarity matrics 
from sklearn.metrics.pairwise import cosine_similarity, euclidean_distances
similarity_cosine = cosine_similarity(X_train) 
similarity_dot = ng_df_normalized.dot(X_train.T)
similarity_euclidean = euclidean_distances(X_train)
print(similarity_cosine[3:])
print(similarity_dot[3:])
print(similarity_euclidean[3:])

[[0.06169214 0.02758962 0.05552655 ... 0.0907483  0.01769174 0.15917437]
 [0.03359964 0.01889255 0.03132948 ... 0.03541604 0.01673287 0.03870095]
 [0.05203874 0.02656251 0.06475225 ... 0.08282928 0.01790741 0.09668578]
 ...
 [0.08311122 0.0598701  0.15344998 ... 1.         0.03184764 0.23280829]
 [0.03587904 0.01404557 0.02381214 ... 0.03184764 1.         0.03140382]
 [0.12017145 0.06433675 0.14138402 ... 0.23280829 0.03140382 1.        ]]
  (0, 7899)	0.004520184510495075
  (0, 6779)	0.00389835813228462
  (0, 6309)	0.003197740407500023
  (0, 5276)	0.0031019478091096515
  (0, 1027)	0.006225379119335134
  (0, 6230)	0.007040913066629012
  (0, 5365)	0.012316944934156185
  (0, 3891)	0.016169208090476627
  (0, 3642)	0.005902780083227706
  (0, 1638)	0.005267281662533573
  (0, 6311)	0.019354885136902592
  (0, 3675)	0.007975393174923717
  (0, 3570)	0.013784552159139986
  (0, 7450)	0.006917861569849895
  (0, 7172)	0.00957748884394456
  (0, 6429)	0.010080297718292771
  (0, 5676)	0.004641457111693

In [14]:
### MNIST Data set 
from sklearn.datasets import fetch_openml
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from mlxtend.data import mnist_data
# Load MNIST dataset
X, y = mnist_data()
# Normalize = MinMax
scaler = MinMaxScaler()
X_normalized = scaler.fit_transform(X)
# Compute pairwise similarity matrices using cosine similarity, dot product, and Euclidean distance
from sklearn.metrics.pairwise import cosine_similarity, euclidean_distances
similarity_cosine = cosine_similarity(X_normalized)
similarity_dot = X_normalized.dot(X_normalized.T)
similarity_euclidean = euclidean_distances(X_normalized)
print(similarity_cosine[3:])
print(similarity_dot[3:])
print(similarity_euclidean[3:])

[[0.78084024 0.71902675 0.86654836 ... 0.26305834 0.59395542 0.5038614 ]
 [0.76551118 0.79492976 0.55926789 ... 0.29149068 0.52704736 0.53412199]
 [0.66021855 0.64684846 0.50437021 ... 0.33371686 0.50188698 0.50272051]
 ...
 [0.22097506 0.24326185 0.30540717 ... 1.         0.43995317 0.30329263]
 [0.51607194 0.510324   0.60633877 ... 0.43995317 1.         0.43602397]
 [0.46873101 0.41946966 0.52746328 ... 0.30329263 0.43602397 1.        ]]
[[ 90.22302191  89.39615532 111.01524029 ...  21.47206459  73.13224145
   60.79166474]
 [ 98.4596386  110.01554787  79.75560169 ...  26.48487505  72.23641676
   71.73397924]
 [ 81.49971549  85.9190619   69.03231065 ...  29.10134564  66.01979239
   64.79966167]
 ...
 [ 16.20522876  19.19572472  24.83280277 ...  51.80580828  34.38097655
   23.22477509]
 [ 57.08939639  60.74489812  74.36955017 ...  34.38097655 117.88133795
   50.36552095]
 [ 50.80971934  48.92628989  63.39426374 ...  23.22477509  50.36552095
  113.18812764]]
[[ 7.20919892  8.36712319  5